### ISSUE TITLE
Open API template - Invalid value of the Web service URL

### ISSUE THREAD

**Issue by FergusKidd** [Azure-Samples/openai-python-enterprise-logging#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Create from definition 'Open API' with 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2022-12-01/inference.json' as the specification. and 'openai' as the URL suffix. 

### Any log messages given by the failure
> One or more fields contain incorrect values:
Invalid value of the Web service URL

### Expected/desired behavior
> Creation of new API as per instructions

### OS and Version?
> Azure Portal

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by FergusKidd** [comment]
<img width="1110" alt="Screenshot 2023-04-13 at 10 17 01" src="https://user-images.githubusercontent.com/45766226/231714038-97d82575-1423-4a00-b493-753bfeaff12e.png">

**Comment by jakeatmsft** [comment]
Instructions have been updated, please use the "Import" feature to update an existing API using the OpenAI spec.  It's also recommended to use the **2023-03-15-preview** to include the "chatCompletions" endpoint.

**Comment by FergusKidd** [comment]
Thank you! Working for me now.
