### ISSUE TITLE
Application Gateway not used

### ISSUE THREAD

**Issue by superpoussin22** [Azure-Samples/openai-python-enterprise-logging#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> deploy the structure located in deploy directory following the readme 
> check backend configuration : No backendpool configuration
> in fact the traffic goes from APIM to OpenAI without using the AppGateway

### Any log messages given by the failure
>

### Expected/desired behavior
> Usage of the Application GW to have logs and better security in place

### OS and Version?
>  macOS 

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

@rukasakurai for you  info

**Comment by jakeatmsft** [comment]
Thank you for issue, AppGateway has been removed from design.
