### ISSUE TITLE
How to secure the Azure OpenAI API key in APIM Backend base policy?

### ISSUE THREAD

**Issue by ericthomas1** [Azure-Samples/openai-python-enterprise-logging#12]
### This issue is for a: 
```
- [X] bug report -> please search issues before submitting
- [X] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Deploy this solution as laid out in this repo.

### Issue:

After setting the Backend `base` policy, the Azure OpenAI API key is in **plaintext**. 

**How can this key be stored/retrieved more securely?**

```
<policies>
    <inbound>
        <base />
        <set-header name="api-key" exists-action="append">
            <value>MY_PLAINTEXT_AZURE_OPENAI_API_KEY</value>
        </set-header>
        <set-backend-service base-url="https://<my-openai-resource>.openai.azure.com/openai/" />
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>
```

### Any log messages given by the failure

No errors or messages indicating the behavior.

### Expected/desired behavior

Keys/secrets would not be in plaintext.

### OS and Version?

N/A

### Versions

N/A

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jakeatmsft** [comment]
See this reference for using Key Vault to secure policy keys: https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-properties?tabs=azure-portal

**Comment by ericthomas1** [comment]
Thanks @jakeatmsft. I ended up going with a Named Value + APIM Backend as lined out in #6.
