### ISSUE TITLE
Cant get model lists using APIM

### ISSUE THREAD

**Issue by superpoussin22** [Azure-Samples/openai-python-enterprise-logging#17]
### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
install the chatbot-ui : https://github.com/Patrick-Davis-MSFT/chatbot-ui
don't set-up the AZURE_APIM_KEY variable but put the subscription key in OPENAI_API_KEY( cause we modify in the current repo the header and don't use the Ocp-Apim-Subscription-Key)
the ui will fail with a 500 error in frontend 
on apim logs we have : 
https://xxxxxx.azure-api.net/openai/deployments?api-version=2023-03-15-preview => what fail with a 404 : Unable to match incoming request to an operation.

### Expected/desired behavior
> make it work with current openai-python-enterprise -logging  what is great

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jakeatmsft** [comment]
To extend supported API operations for use with other tools follow these steps:

(Optional) "Append" the following Authoring API endpoints:
Authoring OpenAPI - https://raw.githubusercontent.com/Azure/azure-rest-api-specs/c183bb012de8e9e1d0d2e67a0994748df4747d2c/specification/cognitiveservices/data-plane/AzureOpenAI/authoring/stable/2022-12-01/azureopenai.json

Note: there is a known issue where the backend url will be hardcoded to a raw.githubusercontent.com location for the new operations, these need to be removed in order to route to your azure openai backend.

**Comment by superpoussin22** [comment]
thanks @jakeatmsft  unfortunately it does not work 
https://xxxxxx.azure-api.net/openai/deployments?api-version=2023-03-15-preview
GET https://xxxxxx.azure-api.net/openai/deployments?api-version=2023-03-15-preview HTTP/1.1
Host: xxxxxx.azure-api.net

HTTP/1.1 400 Bad Request
accept-ranges: bytes
content-length: 20
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: text/plain; charset=utf-8
cross-origin-resource-policy: cross-origin
date: Fri, 30 Jun 2023 18:19:07 GMT
expires: Fri, 30 Jun 2023 18:24:07 GMT
strict-transport-security: max-age=31536000
vary: Authorization,Accept-Encoding,Origin,Origin
via: 1.1 varnish
x-cache: MISS
x-cache-hits: 0
x-content-type-options: nosniff
x-fastly-request-id: 07a1de545820c277d5a40f21c3496a41b2c4c009
x-frame-options: deny
x-github-request-id: 0EF0:0E91:1F2E98D:2066D03:649F1C9A
x-served-by: cache-ams21073-AMS
x-timer: S1688149147.449218,VS0,VE101
x-xss-protection: 1; mode=block
    
400: Invalid request

sounds like this is hardcoded :( do you point me the right direction to modify the hardcoded url please ?
thanks in advance

**Comment by superpoussin22** [comment]
never mind found and it works :) 
thanks
