### ISSUE TITLE
Feature change request for logging

### ISSUE THREAD

**Issue by rguikers** [Azure-Samples/openai-python-enterprise-logging#2]
Request and response sizes for embedding usage are too large. request and response json is capped to 8196 bytes
Feature request to solve this with another way of logging outside the max 8196 request/response size of APIM 

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run system as usual

### Any log messages given by the failure
> No failure, but logging request and response limit reached (max 8196 bytes)

### Expected/desired behavior
> Full log in diagnostic log service

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jakeatmsft** [comment]
Thank you for logging this, we are aware of the limitation, for most text completion use cases the 8k payload size is sufficient.  Please follow for updates regarding increase of log size.

**Comment by rguikers** [comment]
Thanks @jakeatmsft ,
In the mean-time, what would in your opinion be the best component to log complete requests/responses from a custom policy. CosmosDB or any other solution?

Thanks in advance,

**Comment by SOE-YoungS** [comment]
I'm facing this issue too. 

Is there anyway to prevent the returned embedding vectors from being logged? As the pertinent info required for monitoring is the remainder of the structure (token count / model etc...), minus "data\embedding".

**Comment by jakeatmsft** [comment]
Please see advanced-logging capabilities for logging over 8k payload size.

**Comment by SOE-YoungS** [comment]
> Please see advanced-logging capabilities for logging over 8k payload size.

Where would one find this?

**Comment by jakeatmsft** [comment]
> > Please see advanced-logging capabilities for logging over 8k payload size.
> 
> Where would one find this?

https://github.com/Azure-Samples/openai-python-enterprise-logging/tree/main/advanced-logging

This shows how you can filter and only log certain payload info using APIM policy.
