### ISSUE TITLE
Error 500 on apim when trying to log

### ISSUE THREAD

**Issue by superpoussin22** [Azure-Samples/openai-python-enterprise-logging#21]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
simply add the policy in apim and try to use the api 

### Any log messages given by the failure
Invalid response object from API: '{ "statusCode": 500, "message": "Internal server error", "activityId": "834f68c5-0cd6-4b3b-8328-c47ab7b7ae88" }' (HTTP response code was 500)

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by superpoussin22** [comment]
more details :
it occurs when openai is in streaming mode , but works fine in "block mode"

**Comment by superpoussin22** [comment]
@SOE-YoungS any idea ? 

thanks in advance

**Comment by SOE-YoungS** [comment]
Best guess here, but enable trace on the API calls and check that there isn't a null ref being thrown on the API policy (specifically in the logging section).

The request is likely not sending back tokens or something like that, so the policy will need to be updated to include the expected response for a streamed item, VS the full response its configured for currently.

**Comment by jakeatmsft** [comment]
I can confirm that token information is not present when using "stream=true", policy will have to be updated.  Please note that streaming experience will differ from calls directly to model endpoint as the logging causes requests to buffer.  
For more information: https://learn.microsoft.com/en-us/azure/api-management/how-to-server-sent-events

**Comment by emocibob** [comment]
I deployed the basic reference architecture, and I also got a 500 error when I tried to test the API in the Azure portal. Error message:

```
{
    "statusCode": 500,
    "message": "Internal server error",
    "activityId": "37cbb03c-a855-440d-9dce-7c25131fe16e"
}
```

I found this additional error in the "Backend" trace section after tracing my test requests:

```
forward-request (7.849 ms)
{
    "messages": [
        "Error occured while calling backend service.",
        "The remote name could not be resolved: 'REDACTED.openai.azure.com'"
    ]
}
```

I tried the following things without success:

- Checked that the API management instance and the Azure OpenAI instance are in the same virtual network
- Allowed all incoming traffic to the Azure OpenAI instance via its networking settings
- Opened all ports, both inbound and outbound, in the network security group used by the API management subnet
- Added the "Microsoft.CognitiveServices" service endpoint to the API management and Azure OpenAI subnets
- Checked the network status for the API management instance under Network > Network status. All endpoints are green.
- Checked that the API management instance is using external VNet mode
- Checked that the virtual network used the default (Azure-provided) DNS server ("[In external VNet mode, Azure manages the DNS by default](https://learn.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet?tabs=stv2#custom-dns-server-setup)")

Also, it's weird that my `REDACTED.openai.azure.com` endpoint can be resolved from my machine by `ping` and the Python `openai` SDK but not by the API management instance.

**Comment by emocibob** [comment]
I fixed [my 500 error](https://github.com/Azure-Samples/openai-python-enterprise-logging/issues/21#issuecomment-1664044537) by deleting the private endpoint for my Azure OpenAI instance and deleting the related private DNS zone.

I also had to implement [this fix](https://github.com/Azure-Samples/openai-python-enterprise-logging/issues/3#issuecomment-1538759231) to prevent 404 errors when testing my API.

**Comment by jakeatmsft** [comment]
> I fixed [my 500 error](https://github.com/Azure-Samples/openai-python-enterprise-logging/issues/21#issuecomment-1664044537) by deleting the private endpoint for my Azure OpenAI instance and deleting the related private DNS zone.
> 
> I also had to implement [this fix](https://github.com/Azure-Samples/openai-python-enterprise-logging/issues/3#issuecomment-1538759231) to prevent 404 errors when testing my API.

If the AOAI resource is deployed in a private VNET with external access disabled, you will need to deploy the APIM layer into internal networking mode to the same VNET or a VNET that is paired with the AOAI resource to ensure connectivity.  Please note that when doing this the easiest way to test the connectivity will be from a VM deployed to the same private network as the APIM testing features will not work.

**Comment by emocibob** [comment]
@jakeatmsft Thanks for the hint! What if I want to keep the AOAI resource in a private subnet but let clients access the API over the public Internet? Is there a way to expose the API while keeping the AOAI resource private, or do I need another resource in front of the API? (The reference architecture diagram suggests an application gateway?)

**Comment by jakeatmsft** [comment]
> @jakeatmsft Thanks for the hint! What if I want to keep the AOAI resource in a private subnet but let clients access the API over the public Internet? Is there a way to expose the API while keeping the AOAI resource private, or do I need another resource in front of the API? (The reference architecture diagram suggests an application gateway?)

You can use a custom domain name to route clients to your API Gateway: https://learn.microsoft.com/en-us/azure/api-management/configure-custom-domain?tabs=custom
