### ISSUE TITLE
Why two virtual networks instead of one?

### ISSUE THREAD

**Issue by emocibob** [Azure-Samples/openai-python-enterprise-logging#25]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

N/A

### Any log messages given by the failure

N/A

### Expected/desired behavior

Some information about the benefits of using two virtual networks instead of one in `README.md`.

### OS and Version?

N/A

### Mention any other details that might be useful

The reference architecture diagram in `README.md` has two peered virtual networks. The [example deployment code](https://github.com/Azure-Samples/openai-python-enterprise-logging/blob/main/deploy/main.bicep) also contains two virtual networks: "Virtual Network for the App Gateway subnet" (`vnetgateway`) and "Virtual Network for workload" (`vnetapp`).

Since virtual network peering makes "[The virtual networks appear as one for connectivity purposes](https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-peering-overview)", and we limit access to services (like Application GW and API Management) by isolating them in different subnets with individual security groups, I don't see why one virtual network shouldn't be enough.

The accepted answer in [this Q&A thread](https://learn.microsoft.com/en-us/answers/questions/1155991/setup-single-vnet-with-mutple-subnets-or-multiple) seems to agree with me: "Peering VNETs will not add any security over using subnets. Peered VNETs are considered to be one big network, like one VNET is. Furthermore, data that is sent via the peering is costing you money." Also, having one virtual network instead of two lowers maintenance overhead since, e.g., we have fewer Bicep or Terraform resources and less code.

**Comment by jakeatmsft** [comment]
The multiple VNets follows our Azure Architecture Hub and Spoke model, it is completely optional, but it is a common pattern for existing Enterprise Azure Customers: https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/hybrid-networking/hub-spoke?tabs=cli
