### ISSUE TITLE
receiving 404 status code in python lambda function

### ISSUE THREAD

**Issue by yousef000** [Azure-Samples/openai-python-enterprise-logging#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
import openai
openai.api_type = "azure"
openai.api_base = "https://xxxxxxxxx.azure-api.net/" # APIM Endpoint
openai.api_version = "2023-03-15-preview"
openai.api_key = "APIM SUBSCRIPTION KEY" #DO NOT USE ACTUAL AZURE OPENAI SERVICE KEY

response = openai.Completion.create(engine="modelname",  
                                    prompt="prompt text", temperature=1,  
                                    max_tokens=200,  top_p=0.5,  
                                    frequency_penalty=0,  
                                    presence_penalty=0,  
                                    stop=None) 

### Any log messages given by the failure
> 404 Resource Not Found. The reason why it's giving 404 is because openai library appends "openai" to url in every request like this: https://xxxxxx.azure-api.net/openai/deployments/text-davinci-003/completions?api-key=2022-12-01, but the apim url is https://xxxxxx.azure-api.net/deployments/text-davinci-003/completions?api-key=2022-12-01. In order to fix it, remove "openai" from backend service url and add "openai" to each operation url like this: /openai/deployments/{deployment_id}/completions?api-version={api_version}

### Expected/desired behavior
> receiving 200 status code

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jakeatmsft** [comment]
This step in the instructions should solve this issue:

Step:
**Configure the backend service to the endpoint of your deployed OpenAI service with /openai as the path, be sure to override the existing endpoint:
Example: https://< yourservicename >.openai.azure.com/openai**

**Comment by AnkitSDesai** [comment]
@jakeatmsft  tried it both APIM and backend url but seems to have same issue any thoughts?

**Comment by jakeatmsft** [comment]
Can you provide the error message you are receiving?

**Comment by AnkitSDesai** [comment]
Seems like it is not able to find the endpoint from APIM to be able to call hence 404
raise error.APIError(
openai.error.APIError: Invalid response object from API: '{ "statusCode": 404, "message": "Resource not found" }' (HTTP response code was 404)

**Comment by yousef000** [comment]
Hey Ankit, this worked for me. Remove "openai" from backend service url and add "openai" to each operation url like this: /openai/deployments/{deployment_id}/completions?api-version={api_version}.

**Comment by jakeatmsft** [comment]
Marking issue closed
