### ISSUE TITLE
Kusto OperaionId case sensitive

### ISSUE THREAD

**Issue by HakjunMIN** [Azure-Samples/openai-python-enterprise-logging#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Looks miss case of Kusto query for retrieving log at README.md 

```kusto
ApiManagementGatewayLogs
| where OperationId == 'completions_create'
...
```
This should be `OperationId== 'Completions_Create'` since `OperationId` is case sensitive. It occurs twice at README

### Any log messages given by the failure
>
No found in logs
### Expected/desired behavior
>
N/A

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
N/A
### Versions
>
N/A
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jakeatmsft** [comment]
Updated kusto queries, thank you!
