### ISSUE TITLE
Unable to test from within the APIM resource

### ISSUE THREAD

**Issue by ericthomas1** [Azure-Samples/openai-python-enterprise-logging#6]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

I've closely followed the docs, but testing *in the APIM resource* fails with Status 400 Model Error. While testing in Postman is successful.

```
{
    "error": {
        "code": "401",
        "message": "Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."
    }
}
```

### Minimal steps to reproduce

1. Import the [OpenAI OpenAPI spec listed in the docs](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-03-15-preview/inference.json), as a new HTTP API.
2. In `Settings` set the `Subscription` - header name to "api-key"
3. Get the OpenAI API key for the Azure OpenAI resource
4. Configure the `set-headers` rule; paste in the OpenAI API key
5. Configure the backend HTTPS endpoint to be the OpenAI endpoint with `/openai` appended
    - ![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/0339fb48-f921-4595-bc44-66859292368e)
6. Click `Test`
7. Enter the `deployment-id` (<name of the deployed model>), enter the `api-version` (`2023-03-15-preview`)
8. Enter a POST body
```
{
  "messages": [
    {
      "content": "You are an expert",
      "role": "system"
    },
    {
      "content": "Encourage the user",
      "role": "assistant"
    },
    {
      "content": "Am I cool?",
      "role": "user"
    }
  ]
}
```
9. Results are the error error shown above
10. I tried adding the `api-key` header in the test area, same error

When I test using the exact same setup, in Postman, with the `api-key` header set, the result is a Status 200.

### Any log messages given by the failure
>

### Expected/desired behavior
- Shown above

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11

### Versions
Current

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jakeatmsft** [comment]
Please ensure that the set-header operation for the "api-key" is set to "Override" on the Inbound Processing policy.

**Comment by SOE-YoungS** [comment]
The correct way to do this is to create a named value and set its value to your AOAI Resources Key1 value.
Key1 should be stored in an Azure Key Vault. If it is ever compromised, the key can be rotated via the Key Vault without any modification to the API instance.

Then in APIM > Backends, create a new backend and point it at your AOAI resources URL.
![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/95053834/2be79236-8cbe-471a-95e7-422abea19146)

Under Authorization for the backend, set a new header named "api-key" and set its value to the named value.
![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/95053834/eaab3fb0-aed9-4dec-96ea-6f7520f54764)

Then build out your API policy as below.
![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/95053834/829cf14c-c979-4228-b7ab-9f8449a1a5e1)

To enable API usage via existing libraries, such as Semantic Kernel etc... you can also adjust the "Subscription" settings for the API to the following,
![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/95053834/f0f15043-73dc-4f1d-bbde-5a7ff02c755f)

In the calling client (using the library), you then set the "OpenAI / Azure OpenAI" URL & Key to the values for your API base URL / APIM subscription key.

**Comment by jakeatmsft** [comment]
Thank you for this contribution, please open PR, happy to include your setup steps.

**Comment by ericthomas1** [comment]
> ...create a named value and set its value...

Where is this done?

**Comment by ericthomas1** [comment]
Please disregard. I found it under `APIs` in the APIM resource:
![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/ca20660f-3d3a-4047-82f5-be72ee05a1bb)

**Comment by ericthomas1** [comment]
Hm... After setting up APIM using the method above, and sending a test request, I receive:

```
{
    "error": {
        "code": "404",
        "message": "Resource not found"
    }
}
```

**Here is my setup**:

1. Created a new Key Vault Resource
2. Created a new Key Vault Secret with value set to the my Azure OpenAI Resource Key1
3. Since I use RBAC, I ensured the APIM resource has `Secrets User` Role assigned
     - ![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/c4cea824-5eb0-46da-9388-f2958f59e5bf)
4. Added a Named Value to my APIM resource, selecting the correct Key Vault and Secret
    - ![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/de9e872a-b10b-41d3-a2e2-53ec551bf277)
5. Added a new Backend to my APIM resource pointing the `Runtime URL` to my Azure OpenAI resource URL
    - ![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/c206561a-4e09-4cd3-865f-cb8972ed4471)
6. Under `Authorization credentials` I added an `api-key` header and pointed it to the Named Value created earlier
    - ![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/c844bb13-dbaf-4055-a983-846107f46991)
7. I then edited the existing APIM API policy for All Operations
    - From...
         - ![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/8c7c8461-cee1-4a09-aab2-0cd53740f55d)
    - To...
        - ![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/c2f7ba2e-16eb-468c-b7f3-6652e3450947)
8. I already had Subscriptions enabled and requests were successful. However now, they result in Status 404:
    - ![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/5c2fcf7f-168f-4724-ae67-62ed7d5c7d0b)

Thoughts on what would cause this?

Thank you

**Comment by SOE-YoungS** [comment]
> Hm... After setting up APIM using the method above, and sending a test request, I receive:
> 
> ```
> {
>     "error": {
>         "code": "404",
>         "message": "Resource not found"
>     }
> }
> ```
> 
> **Here is my setup**:
> 
> 1. Created a new Key Vault Resource
> 2. Created a new Key Vault Secret with value set to the my Azure OpenAI Resource Key1
> 3. Since I use RBAC, I ensured the APIM resource has `Secrets User` Role assigned
>    
>    * ![image](https://user-images.githubusercontent.com/42788729/252791759-c4cea824-5eb0-46da-9388-f2958f59e5bf.png)
> 4. Added a Named Value to my APIM resource, selecting the correct Key Vault and Secret
>    
>    * ![image](https://user-images.githubusercontent.com/42788729/252792228-de9e872a-b10b-41d3-a2e2-53ec551bf277.png)
> 5. Added a new Backend to my APIM resource pointing the `Runtime URL` to my Azure OpenAI resource URL
>    
>    * ![image](https://user-images.githubusercontent.com/42788729/252792592-c206561a-4e09-4cd3-865f-cb8972ed4471.png)
> 6. Under `Authorization credentials` I added an `api-key` header and pointed it to the Named Value created earlier
>    
>    * ![image](https://user-images.githubusercontent.com/42788729/252793118-c844bb13-dbaf-4055-a983-846107f46991.png)
> 7. I then edited the existing APIM API policy for All Operations
>    
>    * From...
>      
>      * ![image](https://user-images.githubusercontent.com/42788729/252793713-8c7c8461-cee1-4a09-aab2-0cd53740f55d.png)
>    * To...
>      
>      * ![image](https://user-images.githubusercontent.com/42788729/252793844-c2f7ba2e-16eb-468c-b7f3-6652e3450947.png)
> 8. I already had Subscriptions enabled and requests were successful. However now, they result in Status 404:
>    
>    * ![image](https://user-images.githubusercontent.com/42788729/252796207-5c2fcf7f-168f-4724-ae67-62ed7d5c7d0b.png)
> 
> Thoughts on what would cause this?
> 
> Thank you

Append "/openai" to the end of your Runtime URL in the backend.

**Comment by ericthomas1** [comment]
Thank you @SOE-YoungS ! That worked!

**Comment by ericthomas1** [comment]
@SOE-YoungS, this Backend approach does not require any "override", correct?

In the [original docs](https://github.com/Azure-Samples/openai-python-enterprise-logging#api-management-config), the `api-key` must be set to "override". But this seems to be not required with the Backend approach, correct?

![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/50640381-a431-4e88-8b6a-751e6253a02e)

**Comment by SOE-YoungS** [comment]
Override is not needed when using the backend approach.

The "api-key" header sent from the client should be set to the APIM Subscription key.

The "api-key" header in use between APIM and the Backend is set in the "Authorization Credentials" section of the backend :)
It is automatically added / overridden by APIM when frontend is passed to backend.

However, by setting "api-key" in the clients header, it allows for the use of AI libraries, as APIM validates the callers "api-key" against their subscription & if access is granted, then overrides it and makes the call to the backend. The caller won't see any difference in usage to what the library expects, beyond the fact that the URL is pointing at an APIM endpoint.

I use this method with [Semantic Kernel](https://learn.microsoft.com/en-us/semantic-kernel/overview/).

**Comment by SOE-YoungS** [comment]
> Thank you for this contribution, please open PR, happy to include your setup steps.

Opened [PR #19](https://github.com/Azure-Samples/openai-python-enterprise-logging/pull/19)
