### ISSUE TITLE
GPT-4 model logs not fully appearing in ApiManagementGatewayLogs

### ISSUE THREAD

**Issue by ericthomas1** [Azure-Samples/openai-python-enterprise-logging#8]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
When using gpt-4, there are several parameters that are **not** being logged.

**Examples**:
- `OperationId` is `ChatCompletions_Create` not `completions_create` as lined out in the docs
- `model`, `prompttokens`, `responsetokens` etc. columns are not being `expanded` and are not present in the table because `BackendResponseBody` contains no data even after many successful queries to APIM.

**Example**: This KQL query yields no results, just empty data

```
ApiManagementGatewayLogs
| project BackendResponseBody
```
How do we log GPT-4 models using this solution?

### Minimal steps to reproduce
- The formal docs

### Any log messages given by the failure
- Fails silently

### Expected/desired behavior
- The same verboseness shown in the log examples would be present with GPT-4 models as well.

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ericthomas1** [comment]
Thoughts on this one?

**Comment by ericthomas1** [comment]
Hello,

**I really need to know if**:

a. This solution works with GPT-4 OR
b. If I'm doing something wrong 

I have the solution deployed, but again, I don't see the proper logs when queried through KQL.

Thank you

**Comment by ericthomas1** [comment]
Hello,

Does anyone have any insights on this?

**Comment by ericthomas1** [comment]
@jakeatmsft, could you advise on this item?

**When using this solution with a GPT-4 model...**

![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/4f8b93fb-eba2-42cb-9dec-47ece88abd0c)

**The given queries do not work...***

![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/d60bdb43-1bc4-43e6-a973-2da8c24550a3)

![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/5bbfc5cd-0df7-487d-83ae-21ee9f3e8079)

![image](https://github.com/Azure-Samples/openai-python-enterprise-logging/assets/42788729/1711544f-62c4-4ead-a403-3bc9f100d0fb)

It seems that there is no `BackendResponseBody` column to parse. 

**Need to know**:
- Am I doing something incorrect? OR
- Does this solution only work for GPT-3 models?

**Comment by ericthomas1** [comment]
Addressed here https://github.com/MicrosoftDocs/architecture-center/issues/4073

**Comment by ankit302** [comment]
Use this query it will work;

ApiManagementGatewayLogs
| where OperationId  == 'ChatCompletions_Create'
| extend model = tostring(parse_json(BackendResponseBody)['model'])
| extend prompttokens = parse_json(parse_json(BackendResponseBody)['usage'])['prompt_tokens']
| extend completiontokens = parse_json(parse_json(BackendResponseBody)['usage'])['completion_tokens']
| extend total_tokens = parse_json(parse_json(BackendResponseBody)['usage'])['total_tokens']
